[pytest]
markers =
    sanity: basic smoke tests
    validation: input validation tests
    functionality: positive functionality testing
    error_handling: error handling tests
    edge_cases: edge case tests
    excel_sanity: excel sanity tests
    excel_functionality: positive functionality testing
    bot: whatsapp bot tests
    security: security tests
    load: load tests
    bot_sanity: bot sanity tests
    bot_functionality: bot functionality tests
    bot_error_handling: bot error handling tests
    bot_e2e : bot e2e tests
    bot_load: bot load tests
    selenium: selenium tests

#will exclude the selenium tests (2) which are not directly test our bot and
addopts = -m "not selenium"