[pytest]
markers =
    sanity: basic smoke tests
    validation: input validation tests
    functionality: positive functionality testing
    error_handling: error handling tests
    edge_cases: edge case tests
    excel_sanity: excel sanity tests
    excel_functionality: positive functionality testing
    bot: whatsapp bot tests
    security: security tests
    load: load tests